"""Protocol classes for hardware interface abstraction.

These define the contracts that both real and mock implementations must satisfy.
All protocols are runtime-checkable for isinstance() verification.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, runtime_checkable

from hapticore.core.messages import Command, CommandResponse, HapticState


@runtime_checkable
class HapticInterface(Protocol):
    """Interface for haptic device communication."""

    def get_latest_state(self) -> HapticState | None: ...
    def send_command(self, cmd: Command) -> CommandResponse: ...
    def subscribe_state(self, callback: Callable[[HapticState], None]) -> None: ...
    def unsubscribe_state(self) -> None: ...


@runtime_checkable
class NeuralRecordingInterface(Protocol):
    """Interface for neural recording systems (Ripple, SpikeGLX)."""

    def start_recording(self, filename: str) -> None: ...
    def stop_recording(self) -> None: ...
    def is_recording(self) -> bool: ...
    def get_timestamp(self) -> float: ...


@runtime_checkable
class SyncInterface(Protocol):
    """Interface for hardware sync (Teensy)."""

    def send_event_code(self, code: int) -> None: ...
    def start_sync_pulses(self) -> None: ...
    def stop_sync_pulses(self) -> None: ...
    def is_running(self) -> bool: ...


@runtime_checkable
class DisplayInterface(Protocol):
    """Interface for visual stimulus display (PsychoPy)."""

    def update_scene(self, scene_state: dict[str, Any]) -> None: ...
    def show_stimulus(self, stim_id: str, params: dict[str, Any]) -> None: ...
    def hide_stimulus(self, stim_id: str) -> None: ...
    def clear(self) -> None: ...
    def get_flip_timestamp(self) -> float | None: ...
